webtalk_init -webtalk_dir /ad/eng/users/n/m/nmadayag/EC535/EC535-Final-Project-RISC-V-CPU/RISC-V CPU/RISC-V CPU.sim/sim_1/behav/xsim/xsim.dir/Control_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Apr 30 19:56:13 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211078688_174135686_206649660_409" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c9a5f559-88c1-4e59-806b-1dadbc82abf3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "01f04f27e61c46c3aa9b0f4308d60c05" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.9.2009 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4590.270 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124808_KB" -context "xsim\\usage"
webtalk_transmit -clientid 224679353 -regid "211078688_174135686_206649660_409" -xml /ad/eng/users/n/m/nmadayag/EC535/EC535-Final-Project-RISC-V-CPU/RISC-V CPU/RISC-V CPU.sim/sim_1/behav/xsim/xsim.dir/Control_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /ad/eng/users/n/m/nmadayag/EC535/EC535-Final-Project-RISC-V-CPU/RISC-V CPU/RISC-V CPU.sim/sim_1/behav/xsim/xsim.dir/Control_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /ad/eng/users/n/m/nmadayag/EC535/EC535-Final-Project-RISC-V-CPU/RISC-V CPU/RISC-V CPU.sim/sim_1/behav/xsim/xsim.dir/Control_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
